#!/bin/bash
# ./dl to LX16

scp build/Deployment/letux-esp-serial-flasher.bin/bin/mipsel-linux-gnu/letux-esp-serial-flasher root@192.168.0.202:/usr/local/bin/mipsel-linux-gnu

case "$1" in
	-fw ) # install firmware
		# use rsync?
		ssh root@192.168.0.202 mkdir -p /lib/firmware/espressif/esp32-c6-wroom-1/
		scp ./lib/firmware/espressif/esp32-c6-wroom-1/*.bin root@192.168.0.202:/lib/firmware/espressif/esp32-c6-wroom-1/
		;;
esac